### ISSUE TITLE
Teleporter in Dedicated Server

### ISSUE THREAD

**Issue by munsterlander** [laanp/Icarus_Mods_Separated#4]
QQ, do you need to install your mod on the server and with each player or only on the server?  As is, we have it installed on the server and each player - works great - but we experience intermittent unreal engine crashes.  Any thoughts?

**Comment by laanp** [comment]
That teleporter mod inside my mod is Jimk72's earlier version of the teleporter, and I am just keeping it in there for backwards compatibility.  I would recommend trying out my new "laanp-BeaconTeleport" mod that allows you to teleport to any Portable Beacon location - way better since it supports up to 20 named beacon locations on the map and uses existing names of the beacons, which can also have user selectable icons and colors.  Should work in dedicated server or multiplayer as well.

**Comment by munsterlander** [comment]
That is the one I am talking about and its way better.  BTW, it still says Medical Scan for LMB action.  I presume you modded the HEAL device.
